# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Q1-4.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 544)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(80, 70, 331, 231))
        self.groupBox.setObjectName("groupBox")
        self.button1_1 = QtWidgets.QPushButton(self.groupBox)
        self.button1_1.setGeometry(QtCore.QRect(30, 40, 110, 40))
        self.button1_1.setObjectName("button1_1")
        self.button1_2 = QtWidgets.QPushButton(self.groupBox)
        self.button1_2.setGeometry(QtCore.QRect(30, 100, 110, 40))
        self.button1_2.setObjectName("button1_2")
        self.button1_4 = QtWidgets.QPushButton(self.groupBox)
        self.button1_4.setGeometry(QtCore.QRect(30, 160, 110, 40))
        self.button1_4.setObjectName("button1_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 20, 141, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.button1_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.button1_3.setGeometry(QtCore.QRect(20, 80, 110, 40))
        self.button1_3.setObjectName("button1_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(20, 30, 101, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(80, 330, 171, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.button2 = QtWidgets.QPushButton(self.groupBox_3)
        self.button2.setGeometry(QtCore.QRect(20, 60, 131, 41))
        self.button2.setObjectName("button2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(260, 330, 151, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.button4 = QtWidgets.QPushButton(self.groupBox_4)
        self.button4.setGeometry(QtCore.QRect(20, 60, 111, 41))
        self.button4.setObjectName("button4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(440, 70, 301, 411))
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 30, 261, 291))
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(19, 29, 221, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_angle = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_angle.setGeometry(QtCore.QRect(70, 30, 91, 31))
        self.lineEdit_angle.setObjectName("lineEdit_angle")
        self.lineEdit_scale = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_scale.setGeometry(QtCore.QRect(70, 70, 91, 31))
        self.lineEdit_scale.setObjectName("lineEdit_scale")
        self.lineEdit_tx = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_tx.setGeometry(QtCore.QRect(70, 110, 91, 31))
        self.lineEdit_tx.setObjectName("lineEdit_tx")
        self.lineEdit_ty = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_ty.setGeometry(QtCore.QRect(70, 150, 91, 31))
        self.lineEdit_ty.setObjectName("lineEdit_ty")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setGeometry(QtCore.QRect(30, 40, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setGeometry(QtCore.QRect(170, 40, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setGeometry(QtCore.QRect(170, 116, 47, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setGeometry(QtCore.QRect(170, 150, 47, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.button3_1 = QtWidgets.QPushButton(self.groupBox_6)
        self.button3_1.setGeometry(QtCore.QRect(20, 240, 221, 41))
        self.button3_1.setObjectName("button3_1")
        self.button3_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.button3_2.setGeometry(QtCore.QRect(40, 340, 221, 41))
        self.button3_2.setObjectName("button3_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "1. Calibration"))
        self.button1_1.setText(_translate("MainWindow", "1.1 Find Corners"))
        self.button1_2.setText(_translate("MainWindow", "1.2 Intrinsic"))
        self.button1_4.setText(_translate("MainWindow", "1.4 Distortion"))
        self.groupBox_2.setTitle(_translate("MainWindow", "1.3 Extrinsic"))
        self.button1_3.setText(_translate("MainWindow", "1.3 Extrinsic"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox.setItemText(14, _translate("MainWindow", "15"))
        self.groupBox_3.setTitle(_translate("MainWindow", "2. Augmented Reality"))
        self.button2.setText(_translate("MainWindow", "2.1 Augmented Reality"))
        self.groupBox_4.setTitle(_translate("MainWindow", "4. Find Contour"))
        self.button4.setText(_translate("MainWindow", "4.1 Find Contour"))
        self.groupBox_5.setTitle(_translate("MainWindow", "3. Image Transformation"))
        self.groupBox_6.setTitle(_translate("MainWindow", "3.1 Rotate, Scale, Translate"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Parameters"))
        self.label.setText(_translate("MainWindow", "Angle:"))
        self.label_2.setText(_translate("MainWindow", "Scale:"))
        self.label_3.setText(_translate("MainWindow", "Tx:"))
        self.label_4.setText(_translate("MainWindow", "Ty:"))
        self.label_5.setText(_translate("MainWindow", "deg"))
        self.label_6.setText(_translate("MainWindow", "pixel"))
        self.label_7.setText(_translate("MainWindow", "pixel"))
        self.button3_1.setText(_translate("MainWindow", "3.1 Rotate, Scale, Translate"))
        self.button3_2.setText(_translate("MainWindow", "3.2 Perspective Transform"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

